-- ESERCIZIO PROVA --

CREATE TABLE esercizioProva (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Prova_1` VARCHAR(45) NULL,
  `Prova_2` VARCHAR(45) NULL);

ALTER TABLE esercizioProva ADD PRIMARY KEY (`id`);
